Work file
# Brew 
zsh
tmux
vim
coreutils
binutils
diffutils
ed
findutils
gawk
gnu-indent
gnu-sed
gnu-which
gnutls
grep
gzip
screen
watch
wdiff
wget
iprout2mac
bash
emacs
gpatch
less
m4
make
nano
gdb
file-formula
git
openssh
perl
rsync
svn
unzip

# Brew dependencies


# Casks
alfred
anki
devdocs
docker
dropbox
firefox-developer-edition
font-3270-nerd-font
font-inconsolata-for-powerline
font-inconsolata-go-nerd-font
font-inconsolata-nerd-font
font-meslo-lg-nerd-font
font-proggy-clean-tt-nerd-font
font-roboto-mono-nerd-font
google-chrome
hammerspoon
intellij-idea-ce
iterm2
microsoft-auto-update
microsoft-excel
microsoft-outlook
microsoft-powerpoint
microsoft-teams
microsoft-word
postman
pycharm-ce
slack
spotify
the-unarchiver
virtualbox
virtualbox-extension-pack
vlc
