# Set theme and default user
ZSH_THEME="powerlevel9k/powerlevel9k"
DEFAULT_USER="coffie"

# Powerlevel 9k configuration
# Set left and right prompt
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status battery ram ip)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)

# Battery configuration
POWERLEVEL9K_BATTERY_LOW_BACKGROUND="black"
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND="black"
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND="black"
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND="black"
POWERLEVEL9K_BATTERY_LOW_FOREGROUND="red"
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND="yellow"
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND="green"
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND="249"
POWERLEVEL9K_BATTERY_VERBOSE=false
POWERLEVEL9K_BATTERY_LOW_THRESHOLD=10

POWERLEVEL9K_TIME_BACKGROUND="black"
POWERLEVEL9K_TIME_FOREGROUND=249
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

POWERLEVEL9K_IP_BACKGROUND="black"
POWERLEVEL9K_IP_FOREGROUND=249

POWERLEVEL9K_RAM_BACKGROUND="black"
POWERLEVEL9K_RAM_FOREGROUND=249

# Directory modification
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

POWERLEVEL9K_RAM_ELEMENTS=(ram_used)
