#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# Status bar

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                float
yabai -m config window_border                on
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xff147698
yabai -m config normal_window_border_color   0xff505050
# yabai -m config insert_window_border_color   0xffd75f5f

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10
yabai -m config external_bar                 all:25:0

# yabai -m config top_padding 26
yabai -m config top_paddign 32

# Do not manage certain applications
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="System Information" manage=off
yabai -m rule --add app="^Plex$" manage=off
yabai -m rule --add app="^VLC$" manage=off
# Don't manage certain windows in applications
yabai -m rule --add app="^rekordbox$" title="Preferences" manage=off
yabai -m rule --add app="^Live$" title="Preferences" manage=off
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Finder Settings)" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="Preferences" manage=off

yabai -m space 1 --label code
yabai -m space 2 --label web
yabai -m space 3 --label comm
yabai -m space 4 --label doc

# yabai -m query --windows | jq ".[] | { App: .app, Title: .title }"

echo "yabai configuration loaded.."
