#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
FONT="Inconsolata Nerd Font Mono" # Needs to have Regular, Bold, Semibold, Heavy and Black variants

sketchybar --bar color=$COLOR_TRANSPARENT   \
                 height=56                  \
                 margin=0                   \
                 y_offset=0                 \
                 padding_left=8             \
                 padding_right=8

sketchybar --default padding_left=8                                  \
                     padding_right=8                                 \
                     background.border_color=$COLOR_YELLOW           \
                     background.border_width=2                       \
                     background.height=40                            \
                     background.corner_radius=12                     \
                     icon.color=$COLOR_YELLOW                        \
                     icon.highlight_color=$COLOR_BACKGROUND          \
                     icon.padding_left=6                             \
                     icon.padding_right=2                            \
                     icon.font="$FONT:Regular:16.0"                  \
                     label.color=$COLOR_YELLOW                       \
                     label.highlight_color=$COLOR_BACKGROUND         \
                     label.padding_left=2                            \
                     label.padding_right=6                           \
                     label.font="$FONT:Regular:12.0"


# Items

sketchybar --add item  ip_address right                              \
           --set       ip_address script="$PLUGIN_DIR/ip_address.sh" \
                                  update_freq=30                     \
                                  padding_left=2                     \
                                  padding_right=8                    \
                                  background.border_width=0          \
                                  background.corner_radius=6         \
                                  background.height=24               \
                                  icon.highlight=on                  \
                                  label.highlight=on                 \
           --subscribe ip_address wifi_change                        \
                                                                     \
           --add item  volume right                                  \
           --set       volume script="$PLUGIN_DIR/volume.sh"         \
                              padding_left=2                         \
                              padding_right=2                        \
                              background.border_width=0              \
                              background.height=24                   \
           --subscribe volume volume_change                          \
                                                                     \
           --add item  battery right                                 \
           --set       battery script="$PLUGIN_DIR/battery.sh"       \
                               update_freq=120                       \
                               padding_left=8                        \
                               padding_right=2                       \
                               background.border_width=0             \
                               background.height=24                  \
           --subscribe battery system_woke power_source_change       \
                                                                     \
           --add item  slack right                                   \
           --set       slack script="$PLUGIN_DIR/slack.sh"           \
                             update_freq=180                         \
                             background.padding_left=15              \
                             icon.font.size=30                       \
           --subscribe slack system_woke

##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces

sketchybar --add event window_change

COLORS_SPACE=($COLOR_YELLOW $COLOR_CYAN $COLOR_MAGENTA $COLOR_WHITE $COLOR_BLUE $COLOR_RED $COLOR_GREEN $COLOR_ORANGE $COLOR_PURPLE $COLOR_TEAL $COLOR_YELLOWGREEN $COLOR_PINK)
LENGTH=${#ICONS_SPACE[@]}

for i in "${!ICONS_SPACE[@]}"
do
  sid=$(($i+1))
  PAD_LEFT=2
  PAD_RIGHT=2
  if [[ $i == 0 ]]; then
    PAD_LEFT=8
  elif [[ $i == $(($LENGTH-1)) ]]; then
    PAD_RIGHT=8
  fi
  sketchybar --add space space.$sid left                                       \
             --set       space.$sid script="$PLUGIN_DIR/app_space.sh"          \
                                    associated_space=$sid                      \
                                    padding_left=$PAD_LEFT                     \
                                    padding_right=$PAD_RIGHT                   \
                                    background.color=${COLORS_SPACE[i]}        \
                                    background.border_width=0                  \
                                    background.corner_radius=6                 \
                                    background.height=24                       \
                                    icon=${ICONS_SPACE[i]}                     \
                                    icon.color=${COLORS_SPACE[i]}              \
                                    label="_"                                  \
                                    label.color=${COLORS_SPACE[i]}             \
             --subscribe space.$sid front_app_switched window_change
done

sketchybar --add bracket spaces '/space\..*/'                      \
           --set         spaces background.color=$COLOR_BACKGROUND

sketchybar --add item seperator.l2 left                   \
           --set      seperator.l2 padding_left=4         \
                                   padding_right=4        \
                                   background.drawing=off \
                                   icon.drawing=off       \
                                   label.drawing=off
